# Generated by Django 2.2.6 on 2019-10-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='author',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
